/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed */
        get: operations["feed_api_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backlog */
        get: operations["backlog_api_v1_backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/steps/{step_id}/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark */
        post: operations["mark_api_v1_tasks__task_id__steps__step_id__mark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/steps/{step_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo */
        post: operations["undo_api_v1_tasks__task_id__steps__step_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parse-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Date */
        post: operations["parse_date_api_v1_parse_date_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extract-when": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract When */
        post: operations["extract_when_api_v1_extract_when_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reasons */
        get: operations["reasons_api_v1_reasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacklogResult */
        BacklogResult: {
            /** Now */
            now: string;
            /** Backlog */
            backlog: components["schemas"]["FeedRow"][];
            /** Count */
            count: number;
            /** Broken */
            broken?: string[];
        };
        /** Counts */
        Counts: {
            /** Overdue */
            overdue: number;
            /** Today */
            today: number;
            /** Waiting */
            waiting: number;
        };
        /**
         * ExtractResult
         * @description Быстрый ввод одной строкой: название, дата и границы распознанного куска
         *     в исходном тексте — для подсветки и вырезания из названия.
         */
        ExtractResult: {
            /** Title */
            title: string;
            /** Date */
            date?: string | null;
            /** Label */
            label?: string | null;
            /**
             * Past
             * @default false
             */
            past: boolean;
            /** Span */
            span?: [
                number,
                number
            ] | null;
        };
        /**
         * FeedResult
         * @description Лента «Что сегодня». Просроченное в строки не попадает: по 6.1 оно живёт
         *     отдельной плашкой — пятнадцать красных строк парализуют экран.
         */
        FeedResult: {
            /** Now */
            now: string;
            /** Feed */
            feed: components["schemas"]["FeedRow"][];
            /** Overdue Count */
            overdue_count: number;
            counts: components["schemas"]["Counts"];
            next_ahead: components["schemas"]["FeedRow"] | null;
            /** Stalled Count */
            stalled_count: number;
            /** Broken */
            broken?: string[];
        };
        /**
         * FeedRow
         * @description Строка ленты или завала. Всё вычислено здесь: оболочка только показывает.
         *     Раздел 6.1 ТЗ перечисляет, что видно в строке: название шага, название
         *     задачи, время контроля, теги, счётчик переносов, если больше нуля.
         */
        FeedRow: {
            /** Task Id */
            task_id: number;
            /** Task */
            task: string;
            /** Step */
            step: number;
            /** Title */
            title: string | null;
            /** Group */
            group?: string | null;
            /** Note */
            note?: string | null;
            /** Control At */
            control_at: string | null;
            /** Show At */
            show_at: string | null;
            /** State */
            state: string;
            /** Postponed */
            postponed: number;
            /** Stalled */
            stalled: boolean;
            /** Tags */
            tags: string[];
            /** Last Reason */
            last_reason: string | null;
            /** Actions */
            actions: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MarkIn
         * @description Отметка шага. `to` — человеческий ввод («завтра в 9», «+3», ISO):
         *     разбирает ядро, оболочка дату не трогает (`CONTRACT.md`).
         */
        MarkIn: {
            /** Op */
            op: string;
            /** Reason */
            reason?: string | null;
            /** To */
            to?: string | null;
        };
        /**
         * MarkResult
         * @description Ответ на отметку шага. Несёт новое состояние — обновлённую строку ленты
         *     (`row`, None если шаг из ленты и завала ушёл) и счётчики, — чтобы клиенту
         *     не нужен был второй круг до сервера. Это контрактно чистая версия
         *     оптимистичного интерфейса: оболочка по-прежнему ничего не вычисляет.
         */
        MarkResult: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Op */
            op: string;
            /** Task Id */
            task_id: number;
            /** Task */
            task: string;
            /** Step */
            step: number;
            /** Status */
            status: string;
            /** Task Status */
            task_status: string;
            /** Next Step Id */
            next_step_id?: number | null;
            /** Next Step Title */
            next_step_title?: string | null;
            /** Dates Assigned */
            dates_assigned?: number[];
            /** Next Check */
            next_check?: string | null;
            /**
             * Stalled
             * @default 0
             */
            stalled: number;
            /** Hint */
            hint?: string | null;
            /** Undone */
            undone?: string | null;
            /** Control Date */
            control_date?: string | null;
            row?: components["schemas"]["FeedRow"] | null;
            counts: components["schemas"]["Counts"];
        };
        /**
         * ReasonsResult
         * @description Справочник причин переноса и провала (раздел 5.4 ТЗ). Только активные:
         *     архивная причина для новой записи не годится, а в истории остаётся.
         */
        ReasonsResult: {
            /** Reasons */
            reasons: string[];
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Query */
            query: string;
            /** Count */
            count: number;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** TextIn */
        TextIn: {
            /** Text */
            text?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WhenResult
         * @description Во что превратился человеческий ввод даты — подсказка под полем формы.
         *     Подпись («завтра в 09:30», «18.10.2026, через 40 дн.») считается здесь,
         *     а не в браузере: по контракту оболочка не пересказывает данные ядра
         *     своими словами. Нераспознанный ввод — это ответ, а не ошибка запроса:
         *     поле опрашивается на каждое нажатие клавиши.
         */
        WhenResult: {
            /** Ok */
            ok: boolean;
            /** Date */
            date?: string | null;
            /** Label */
            label?: string | null;
            /**
             * Past
             * @default false
             */
            past: boolean;
            /** Error */
            error?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    feed_api_v1_feed_get: {
        parameters: {
            query?: {
                now?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backlog_api_v1_backlog_get: {
        parameters: {
            query?: {
                now?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_api_v1_tasks__task_id__steps__step_id__mark_post: {
        parameters: {
            query?: {
                now?: string | null;
            };
            header?: never;
            path: {
                task_id: number;
                step_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_api_v1_tasks__task_id__steps__step_id__undo_post: {
        parameters: {
            query?: {
                now?: string | null;
            };
            header?: never;
            path: {
                task_id: number;
                step_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_date_api_v1_parse_date_post: {
        parameters: {
            query?: {
                now?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhenResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_when_api_v1_extract_when_post: {
        parameters: {
            query?: {
                now?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query?: {
                q?: string | null;
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reasons_api_v1_reasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReasonsResult"];
                };
            };
        };
    };
}
